### ISSUE TITLE
broken source?

### ISSUE THREAD

**Issue by Unixware** [djdron/UnrealSpeccyP#4]
something is broken there...
(just some of the last lines of the log)

/usr/include/wx-3.0/wx/event.h:4379:63: note: suggested alternative: ‘wxJoystickEvent’
 #define EVT_JOY_ZMOVE(func) wx__DECLARE_EVT0(wxEVT_JOY_ZMOVE, wxJoystickEventHandler(func))
                                                               ^~~~~~~~~~~~~~~~~~~~~~
/usr/include/wx-3.0/wx/event.h:91:73: note: in definition of macro ‘wxDECLARE_EVENT_TABLE_ENTRY’
     wxEventTableEntry(type, winid, idLast, wxNewEventTableFunctor(type, fn), obj)
                                                                         ^~
/usr/include/wx-3.0/wx/event.h:4150:5: note: in expansion of macro ‘wx__DECLARE_EVT2’
     wx__DECLARE_EVT2(evt, id, wxID_ANY, fn)
     ^~~~~~~~~~~~~~~~
/usr/include/wx-3.0/wx/event.h:4152:5: note: in expansion of macro ‘wx__DECLARE_EVT1’
     wx__DECLARE_EVT1(evt, wxID_ANY, fn)
     ^~~~~~~~~~~~~~~~
/usr/include/wx-3.0/wx/event.h:4379:29: note: in expansion of macro ‘wx__DECLARE_EVT0’
 #define EVT_JOY_ZMOVE(func) wx__DECLARE_EVT0(wxEVT_JOY_ZMOVE, wxJoystickEventHandler(func))
                             ^~~~~~~~~~~~~~~~
/usr/include/wx-3.0/wx/event.h:4386:5: note: in expansion of macro ‘EVT_JOY_ZMOVE’
     EVT_JOY_ZMOVE(func)
     ^~~~~~~~~~~~~
../../platform/wxwidgets/wx_canvas.cpp:88:2: note: in expansion of macro ‘EVT_JOYSTICK_EVENTS’
  EVT_JOYSTICK_EVENTS(GLCanvas::OnJoystickEvent)
  ^~~~~~~~~~~~~~~~~~~
../../platform/wxwidgets/wx_canvas.cpp: In constructor ‘xPlatform::GLCanvas::GLCanvas(wxWindow*)’:
../../platform/wxwidgets/wx_canvas.cpp:94:40: error: class ‘xPlatform::GLCanvas’ does not have any field named ‘eInherited’
 GLCanvas::GLCanvas(wxWindow* parent) : eInherited(parent, wxID_ANY, canvas_attr), mouse_capture(NULL)
                                        ^~~~~~~~~~
../../platform/wxwidgets/wx_canvas.cpp:96:5: error: ‘gl_context’ was not declared in this scope
     gl_context = new wxGLContext(this);
     ^~~~~~~~~~
../../platform/wxwidgets/wx_canvas.cpp:96:5: note: suggested alternative: ‘sigcontext’
     gl_context = new wxGLContext(this);
     ^~~~~~~~~~
     sigcontext
../../platform/wxwidgets/wx_canvas.cpp:96:22: error: expected type-specifier before ‘wxGLContext’
     gl_context = new wxGLContext(this);
                      ^~~~~~~~~~~
../../platform/wxwidgets/wx_canvas.cpp:97:39: error: ‘wxJOYSTICK1’ was not declared in this scope
  joysticks[0] = new eWxJoystick(this, wxJOYSTICK1);
                                       ^~~~~~~~~~~
../../platform/wxwidgets/wx_canvas.cpp:97:39: note: suggested alternative: ‘wxUSE_JOYSTICK’
  joysticks[0] = new eWxJoystick(this, wxJOYSTICK1);
                                       ^~~~~~~~~~~
                                       wxUSE_JOYSTICK
../../platform/wxwidgets/wx_canvas.cpp:98:39: error: ‘wxJOYSTICK2’ was not declared in this scope
  joysticks[1] = new eWxJoystick(this, wxJOYSTICK2);
                                       ^~~~~~~~~~~
../../platform/wxwidgets/wx_canvas.cpp:98:39: note: suggested alternative: ‘wxUSE_JOYSTICK’
  joysticks[1] = new eWxJoystick(this, wxJOYSTICK2);
                                       ^~~~~~~~~~~
                                       wxUSE_JOYSTICK
../../platform/wxwidgets/wx_canvas.cpp: In destructor ‘virtual xPlatform::GLCanvas::~GLCanvas()’:
../../platform/wxwidgets/wx_canvas.cpp:107:12: error: ‘gl_context’ was not declared in this scope
     delete gl_context;
            ^~~~~~~~~~
../../platform/wxwidgets/wx_canvas.cpp:107:12: note: suggested alternative: ‘sigcontext’
     delete gl_context;
            ^~~~~~~~~~
            sigcontext
../../platform/wxwidgets/wx_canvas.cpp: In member function ‘void xPlatform::GLCanvas::OnPaint(wxPaintEvent&)’:
../../platform/wxwidgets/wx_canvas.cpp:114:2: error: ‘wxPaintDC’ was not declared in this scope
  wxPaintDC dc(this);
  ^~~~~~~~~
../../platform/wxwidgets/wx_canvas.cpp:114:2: note: suggested alternative: ‘wxPrintf’
  wxPaintDC dc(this);
  ^~~~~~~~~
  wxPrintf
../../platform/wxwidgets/wx_canvas.cpp:115:8: error: ‘dc’ was not declared in this scope
  Paint(dc);
        ^~
../../platform/wxwidgets/wx_canvas.cpp: At global scope:
../../platform/wxwidgets/wx_canvas.cpp:120:22: error: variable or field ‘Paint’ declared void
 void GLCanvas::Paint(wxDC& dc)
                      ^~~~
../../platform/wxwidgets/wx_canvas.cpp:120:22: error: ‘wxDC’ was not declared in this scope
../../platform/wxwidgets/wx_canvas.cpp:120:22: note: suggested alternative: ‘wxIf’
 void GLCanvas::Paint(wxDC& dc)
                      ^~~~
                      wxIf
../../platform/wxwidgets/wx_canvas.cpp:120:28: error: ‘dc’ was not declared in this scope
 void GLCanvas::Paint(wxDC& dc)
                            ^~
../../platform/wxwidgets/wx_canvas.cpp: In member function ‘void xPlatform::GLCanvas::OnIdle(wxIdleEvent&)’:
../../platform/wxwidgets/wx_canvas.cpp:135:3: error: ‘GetParent’ was not declared in this scope
   GetParent()->Close(true);
   ^~~~~~~~~
../../platform/wxwidgets/wx_canvas.cpp:141:37: error: variable ‘wxCommandEvent ev’ has initializer but incomplete type
   wxCommandEvent ev(evtSetStatusText);
                                     ^
../../platform/wxwidgets/wx_canvas.cpp:143:3: error: ‘ProcessEvent’ was not declared in this scope
   ProcessEvent(ev);
   ^~~~~~~~~~~~
../../platform/wxwidgets/wx_canvas.cpp:143:3: note: suggested alternative: ‘wxFocusEvent’
   ProcessEvent(ev);
   ^~~~~~~~~~~~
   wxFocusEvent
../../platform/wxwidgets/wx_canvas.cpp:147:3: error: ‘wxClientDC’ was not declared in this scope
   wxClientDC dc(this);
   ^~~~~~~~~~
../../platform/wxwidgets/wx_canvas.cpp:147:3: note: suggested alternative: ‘wxClientData’
   wxClientDC dc(this);
   ^~~~~~~~~~
   wxClientData
../../platform/wxwidgets/wx_canvas.cpp:155:9: error: ‘dc’ was not declared in this scope
   Paint(dc);
         ^~
../../platform/wxwidgets/wx_canvas.cpp: In member function ‘void xPlatform::GLCanvas::OnKeydown(wxKeyEvent&)’:
../../platform/wxwidgets/wx_canvas.cpp:166:12: error: invalid use of incomplete type ‘class wxKeyEvent’
  int key = event.GetKeyCode();
            ^~~~~
In file included from /usr/include/wx-3.0/wx/wx.h:24,
                 from ../../platform/wxwidgets/wx_canvas.cpp:25:
/usr/include/wx-3.0/wx/event.h:657:28: note: forward declaration of ‘class wxKeyEvent’
 class WXDLLIMPEXP_FWD_CORE wxKeyEvent;
                            ^~~~~~~~~~
../../platform/wxwidgets/wx_canvas.cpp:171:17: error: invalid use of incomplete type ‘class wxWindow’
    mouse_capture->Close();
                 ^~
In file included from /usr/include/wx-3.0/wx/wx.h:26,
                 from ../../platform/wxwidgets/wx_canvas.cpp:25:
/usr/include/wx-3.0/wx/utils.h:55:28: note: forward declaration of ‘class wxWindow’
 class WXDLLIMPEXP_FWD_CORE wxWindow;
                            ^~~~~~~~
../../platform/wxwidgets/wx_canvas.cpp:175:39: error: variable ‘wxCommandEvent ev’ has initializer but incomplete type
    wxCommandEvent ev(evtExitFullScreen);
                                       ^
../../platform/wxwidgets/wx_canvas.cpp:182:5: error: invalid use of incomplete type ‘class wxKeyEvent’
  if(event.AltDown())  flags |= KF_ALT;
     ^~~~~
In file included from /usr/include/wx-3.0/wx/wx.h:24,
                 from ../../platform/wxwidgets/wx_canvas.cpp:25:
/usr/include/wx-3.0/wx/event.h:657:28: note: forward declaration of ‘class wxKeyEvent’
 class WXDLLIMPEXP_FWD_CORE wxKeyEvent;
                            ^~~~~~~~~~
../../platform/wxwidgets/wx_canvas.cpp:183:5: error: invalid use of incomplete type ‘class wxKeyEvent’
  if(event.ShiftDown()) flags |= KF_SHIFT;
     ^~~~~
In file included from /usr/include/wx-3.0/wx/wx.h:24,
                 from ../../platform/wxwidgets/wx_canvas.cpp:25:
/usr/include/wx-3.0/wx/event.h:657:28: note: forward declaration of ‘class wxKeyEvent’
 class WXDLLIMPEXP_FWD_CORE wxKeyEvent;
                            ^~~~~~~~~~
../../platform/wxwidgets/wx_canvas.cpp: In member function ‘void xPlatform::GLCanvas::OnKeyup(wxKeyEvent&)’:
../../platform/wxwidgets/wx_canvas.cpp:192:12: error: invalid use of incomplete type ‘class wxKeyEvent’
  int key = event.GetKeyCode();
            ^~~~~
In file included from /usr/include/wx-3.0/wx/wx.h:24,
                 from ../../platform/wxwidgets/wx_canvas.cpp:25:
/usr/include/wx-3.0/wx/event.h:657:28: note: forward declaration of ‘class wxKeyEvent’
 class WXDLLIMPEXP_FWD_CORE wxKeyEvent;
                            ^~~~~~~~~~
../../platform/wxwidgets/wx_canvas.cpp:195:5: error: invalid use of incomplete type ‘class wxKeyEvent’
  if(event.AltDown())  flags |= KF_ALT;
     ^~~~~
In file included from /usr/include/wx-3.0/wx/wx.h:24,
                 from ../../platform/wxwidgets/wx_canvas.cpp:25:
/usr/include/wx-3.0/wx/event.h:657:28: note: forward declaration of ‘class wxKeyEvent’
 class WXDLLIMPEXP_FWD_CORE wxKeyEvent;
                            ^~~~~~~~~~
../../platform/wxwidgets/wx_canvas.cpp:196:5: error: invalid use of incomplete type ‘class wxKeyEvent’
  if(event.ShiftDown()) flags |= KF_SHIFT;
     ^~~~~
In file included from /usr/include/wx-3.0/wx/wx.h:24,
                 from ../../platform/wxwidgets/wx_canvas.cpp:25:
/usr/include/wx-3.0/wx/event.h:657:28: note: forward declaration of ‘class wxKeyEvent’
 class WXDLLIMPEXP_FWD_CORE wxKeyEvent;
                            ^~~~~~~~~~
../../platform/wxwidgets/wx_canvas.cpp: In member function ‘void xPlatform::GLCanvas::OnMouseKey(wxMouseEvent&)’:
../../platform/wxwidgets/wx_canvas.cpp:205:2: error: invalid use of incomplete type ‘class wxMouseEvent’
  event.Skip();
  ^~~~~
In file included from /usr/include/wx-3.0/wx/wx.h:24,
                 from ../../platform/wxwidgets/wx_canvas.cpp:25:
/usr/include/wx-3.0/wx/event.h:654:28: note: forward declaration of ‘class wxMouseEvent’
 class WXDLLIMPEXP_FWD_CORE wxMouseEvent;
                            ^~~~~~~~~~~~
../../platform/wxwidgets/wx_canvas.cpp:208:42: error: cannot convert ‘xPlatform::GLCanvas*’ to ‘wxWindow*’
   mouse_capture = CreateMouseCapture(this);
                                          ^
../../platform/wxwidgets/wx_canvas.cpp:38:40: note:   initializing argument 1 of ‘wxWindow* xPlatform::CreateMouseCapture(wxWindow*)’
 wxWindow* CreateMouseCapture(wxWindow* parent);
                              ~~~~~~~~~~^~~~~~
../../platform/wxwidgets/wx_canvas.cpp: In member function ‘void xPlatform::GLCanvas::OnKillFocus(wxFocusEvent&)’:
../../platform/wxwidgets/wx_canvas.cpp:216:26: error: invalid use of incomplete type ‘class wxWindow’
  SAFE_CALL(mouse_capture)->Close();
                          ^~
In file included from /usr/include/wx-3.0/wx/wx.h:26,
                 from ../../platform/wxwidgets/wx_canvas.cpp:25:
/usr/include/wx-3.0/wx/utils.h:55:28: note: forward declaration of ‘class wxWindow’
 class WXDLLIMPEXP_FWD_CORE wxWindow;
                            ^~~~~~~~
../../platform/wxwidgets/wx_canvas.cpp: In member function ‘void xPlatform::GLCanvas::OnMouseCapture(wxCommandEvent&)’:
../../platform/wxwidgets/wx_canvas.cpp:223:2: error: invalid use of incomplete type ‘class wxCommandEvent’
  event.Skip();
  ^~~~~
In file included from /usr/include/wx-3.0/wx/wx.h:24,
                 from ../../platform/wxwidgets/wx_canvas.cpp:25:
/usr/include/wx-3.0/wx/event.h:653:28: note: forward declaration of ‘class wxCommandEvent’
 class WXDLLIMPEXP_FWD_CORE wxCommandEvent;
                            ^~~~~~~~~~~~~~
../../platform/wxwidgets/wx_canvas.cpp:224:6: error: invalid use of incomplete type ‘class wxCommandEvent’
  if(!event.GetId())
      ^~~~~
In file included from /usr/include/wx-3.0/wx/wx.h:24,
                 from ../../platform/wxwidgets/wx_canvas.cpp:25:
/usr/include/wx-3.0/wx/event.h:653:28: note: forward declaration of ‘class wxCommandEvent’
 class WXDLLIMPEXP_FWD_CORE wxCommandEvent;
                            ^~~~~~~~~~~~~~
../../platform/wxwidgets/wx_canvas.cpp: In member function ‘void xPlatform::GLCanvas::OnJoystickEvent(wxJoystickEvent&)’:
../../platform/wxwidgets/wx_canvas.cpp:232:9: error: invalid use of incomplete type ‘class wxJoystickEvent’
  switch(event.GetJoystick())
         ^~~~~
In file included from /usr/include/wx-3.0/wx/wx.h:24,
                 from ../../platform/wxwidgets/wx_canvas.cpp:25:
/usr/include/wx-3.0/wx/event.h:683:28: note: forward declaration of ‘class wxJoystickEvent’
 class WXDLLIMPEXP_FWD_CORE wxJoystickEvent;
                            ^~~~~~~~~~~~~~~
../../platform/wxwidgets/wx_canvas.cpp:234:7: error: ‘wxJOYSTICK1’ was not declared in this scope
  case wxJOYSTICK1: joysticks[0]->OnEvent(event); break;
       ^~~~~~~~~~~
../../platform/wxwidgets/wx_canvas.cpp:234:7: note: suggested alternative: ‘wxUSE_JOYSTICK’
  case wxJOYSTICK1: joysticks[0]->OnEvent(event); break;
       ^~~~~~~~~~~
       wxUSE_JOYSTICK
../../platform/wxwidgets/wx_canvas.cpp:235:7: error: ‘wxJOYSTICK2’ was not declared in this scope
  case wxJOYSTICK2: joysticks[1]->OnEvent(event); break;
       ^~~~~~~~~~~
../../platform/wxwidgets/wx_canvas.cpp:235:7: note: suggested alternative: ‘wxUSE_JOYSTICK’
  case wxJOYSTICK2: joysticks[1]->OnEvent(event); break;
       ^~~~~~~~~~~
       wxUSE_JOYSTICK
../../platform/wxwidgets/wx_canvas.cpp: In function ‘wxWindow* xPlatform::CreateGLCanvas(wxWindow*)’:
../../platform/wxwidgets/wx_canvas.cpp:244:28: error: cannot convert ‘xPlatform::GLCanvas*’ to ‘wxWindow*’ in return
  return new GLCanvas(parent);
                            ^
make: *** [makefile:52: Release/platform/wxwidgets/wx_canvas.o] Error 1

**Comment by djdron** [comment]
No, wxWidgets build is passed via [appveyor](https://ci.appveyor.com/project/djdron/unrealspeccyp/branch/master).
